const PET_ACTIVITY = ['A_COUCH_POTATO', 'ACTIVE', 'AN_ATHLETE'];

const PET_AGE = ['YOUNG', 'ADULT', 'SENIOR'];

const PET_DEPENDENCY = ['INDEPENDENT', 'SOMEWHAT_DEPENDENT', 'DEPENDENT'];

const PET_EXPERIENCE_LEVEL = ['AN_EXPERT', 'EXPERIENCED', 'A_NOVICE'];

const PET_SEX = ['MALE', 'FEMALE'];

const PET_SIZE = ['SMALL', 'MEDIUM', 'LARGE'];

const PET_SOCIABILITY = ['A_WALL_FLOWER', 'SOCIAL', 'LIFE_OF_THE_PARTY'];

const PET_STATUS = ['ADOPTED', 'NOT_ADOPTED'];

const PET_TRAINABILITY = ['CLASS_CLOWN', 'ATTENTIVE_STUDENT', 'TEACHERS_PET'];

const PET_TYPE = ['DOG', 'CAT', 'NO_PREFERENCE'];

module.exports = {
  PET_ACTIVITY,
  PET_AGE,
  PET_DEPENDENCY,
  PET_EXPERIENCE_LEVEL,
  PET_SEX,
  PET_SIZE,
  PET_SOCIABILITY,
  PET_STATUS,
  PET_TRAINABILITY,
  PET_TYPE,
};
